/**
 * Verso Pagination Engine
 *
 * A deterministic screenplay pagination engine compiled to WebAssembly.
 */

// Types
export type {
  Element,
  ElementType,
  DualDialoguePosition,
  PaperSize,
  MarginConfig,
  ElementStyle,
  ContinuationStyle,
  OrphanControlConfig,
  PageConfig,
  PageIdentifier,
  PageBreakReason,
  LineRange,
  PageElement,
  Page,
  ElementPosition,
  WarningType,
  PaginationWarning,
  PaginationStats,
  PaginationResult,
  LayoutMetadata,
  WorkerRequest,
  WorkerResponse,
  // Incremental pagination types
  ChangeType,
  DocumentChange,
  PaginationCache,
} from './types';

// Utilities
export {
  displayPageIdentifier,
  comparePageIdentifiers,
  // Incremental pagination helpers
  createModifyChange,
  createInsertChange,
  createDeleteChange,
} from './types';

// Serialization
export { serializeDocument, createPositionMap, hasTitlePage, type PositionMap } from './serializer';

// Worker
export { getPaginationWorker, runPagination } from './worker';

// Export functionality
export { exportToFountain, exportToFountainSync, downloadAsFountain, renderForExport } from './export';
export type {
  FontStyle,
  TextItem,
  SceneNumber,
  PageHeader,
  ContinuationMarker,
  RenderedPage,
  TitlePageLayout,
  RenderedDocument,
} from './export';

// PDF export
export { createPdf, downloadPdf, exportToPdf, downloadAsPdf, loadCourierPrimeFonts } from './pdf';

// Layout CSS - derive CSS from WASM config
export { configToCSS, applyLayoutCSS, applyLayoutMetadataCSS, getLayoutConstants, type LayoutCSS } from './layout-css';

// Default configuration
export const DEFAULT_FEATURE_FILM_CONFIG: import('./types').PageConfig = {
  paper_size: 'us_letter',
  lines_per_page: 55,  // Final Draft standard: 9" × 6 LPI
  char_width_pt: 7.2,
  line_height_pt: 12.0,
  margins: {
    top: 1.0,
    bottom: 1.0,  // Industry standard 1" bottom margin
    left: 1.5,
    right: 1.0,
  },
  element_styles: {
    scene_heading: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,  // Final Draft standard: 6" × 10 CPI
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: true,
      keep_with_next_lines: 2,  // Orphan prevention: heading + at least 1 line
      force_uppercase: true,
    },
    action: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,  // Final Draft standard: 6" × 10 CPI
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    character: {
      margin_left: 2.2,
      margin_right: 0,
      max_chars_per_line: 37,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    dialogue: {
      margin_left: 1.0,
      margin_right: 1.5,
      max_chars_per_line: 35,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    parenthetical: {
      margin_left: 1.5,
      margin_right: 2.3,
      max_chars_per_line: 25,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: true,
      keep_with_next_lines: 1,
      force_uppercase: false,
    },
    transition: {
      margin_left: 4.0,
      margin_right: 0,
      max_chars_per_line: 16,
      space_before: 2,
      space_after: 0,  // Match Google AI reference: no bottom margin
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    shot: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    super: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    chyron: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    flashback: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    montage: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    intercut: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    dual_dialogue_left: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    dual_dialogue_right: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    act_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 4,
      space_after: 0,  // Match Google AI reference: no bottom margin
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    page_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    blank_line: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
  },
  continuation_style: {
    more_marker: '(MORE)',
    contd_marker: "(CONT'D)",
    enabled: true,
    // Scene-level continuation (shooting script feature)
    scene_continued_enabled: false,  // Disabled by default
    scene_continued_bottom: '(CONTINUED)',
    scene_continued_top: 'CONTINUED:',
    scene_continued_with_number: false,
  },
  orphan_control: {
    scene_heading_min_following: 2,
    character_min_dialogue_lines: 2,
    dialogue_min_before_split: 2,
    dialogue_min_after_split: 2,
  },
};

// TV Format Configurations
export const DEFAULT_TV_ONE_HOUR_CONFIG: import('./types').PageConfig = {
  paper_size: 'us_letter',
  lines_per_page: 53,
  char_width_pt: 7.2,
  line_height_pt: 12.0,
  margins: {
    top: 1.0,
    bottom: 0.5,
    left: 1.5,
    right: 1.0,
  },
  element_styles: {
    scene_heading: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    action: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    character: {
      margin_left: 2.2,
      margin_right: 0,
      max_chars_per_line: 37,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    dialogue: {
      margin_left: 1.0,
      margin_right: 1.5,
      max_chars_per_line: 35,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    parenthetical: {
      margin_left: 1.5,
      margin_right: 2.3,
      max_chars_per_line: 25,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 1,
      force_uppercase: false,
    },
    transition: {
      margin_left: 4.0,
      margin_right: 0,
      max_chars_per_line: 16,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    shot: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    super: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    chyron: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    flashback: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    montage: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    intercut: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    dual_dialogue_left: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    dual_dialogue_right: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    act_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 4,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    page_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    blank_line: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
  },
  continuation_style: {
    more_marker: '(MORE)',
    contd_marker: "(CONT'D)",
    enabled: true,
  },
  orphan_control: {
    scene_heading_min_following: 2,
    character_min_dialogue_lines: 2,
    dialogue_min_before_split: 2,
    dialogue_min_after_split: 2,
  },
};

export const DEFAULT_TV_HALF_HOUR_CONFIG: import('./types').PageConfig = {
  paper_size: 'us_letter',
  lines_per_page: 53,
  char_width_pt: 7.2,
  line_height_pt: 12.0,
  margins: {
    top: 1.0,
    bottom: 0.5,
    left: 1.5,
    right: 1.0,
  },
  element_styles: {
    scene_heading: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    action: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    character: {
      margin_left: 2.2,
      margin_right: 0,
      max_chars_per_line: 37,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    dialogue: {
      margin_left: 1.0,
      margin_right: 1.5,
      max_chars_per_line: 35,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    parenthetical: {
      margin_left: 1.5,
      margin_right: 2.3,
      max_chars_per_line: 25,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 1,
      force_uppercase: false,
    },
    transition: {
      margin_left: 4.0,
      margin_right: 0,
      max_chars_per_line: 16,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    shot: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    super: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    chyron: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    flashback: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    montage: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    intercut: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    dual_dialogue_left: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    dual_dialogue_right: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    act_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 4,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    page_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    blank_line: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
  },
  continuation_style: {
    more_marker: '(MORE)',
    contd_marker: "(CONT'D)",
    enabled: true,
  },
  orphan_control: {
    scene_heading_min_following: 2,
    character_min_dialogue_lines: 2,
    dialogue_min_before_split: 2,
    dialogue_min_after_split: 2,
  },
};

export const DEFAULT_TV_MULTI_CAM_CONFIG: import('./types').PageConfig = {
  paper_size: 'us_letter',
  lines_per_page: 53,
  char_width_pt: 7.2,
  line_height_pt: 12.0,
  margins: {
    top: 1.0,
    bottom: 0.5,
    left: 1.5,
    right: 1.0,
  },
  element_styles: {
    scene_heading: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    action: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    character: {
      margin_left: 2.2,
      margin_right: 0,
      max_chars_per_line: 37,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    dialogue: {
      margin_left: 1.0,
      margin_right: 1.5,
      max_chars_per_line: 35,
      space_before: 0,
      space_after: 0,
      line_spacing: 2.0,  // Double-spaced for multi-cam
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    parenthetical: {
      margin_left: 1.5,
      margin_right: 2.3,
      max_chars_per_line: 25,
      space_before: 0,
      space_after: 0,
      line_spacing: 2.0,  // Double-spaced for multi-cam
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: true,
      keep_with_next_lines: 1,
      force_uppercase: false,
    },
    transition: {
      margin_left: 4.0,
      margin_right: 0,
      max_chars_per_line: 16,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    shot: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    super: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    chyron: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    flashback: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    montage: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    intercut: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    dual_dialogue_left: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    dual_dialogue_right: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    act_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 4,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    page_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    blank_line: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
  },
  continuation_style: {
    more_marker: '(MORE)',
    contd_marker: "(CONT'D)",
    enabled: true,
  },
  orphan_control: {
    scene_heading_min_following: 2,
    character_min_dialogue_lines: 2,
    dialogue_min_before_split: 2,
    dialogue_min_after_split: 2,
  },
};

// Format Registry
export const FORMAT_CONFIGS = {
  'feature-film': DEFAULT_FEATURE_FILM_CONFIG,
  'tv-one-hour': DEFAULT_TV_ONE_HOUR_CONFIG,
  'tv-half-hour': DEFAULT_TV_HALF_HOUR_CONFIG,
  'tv-multi-cam': DEFAULT_TV_MULTI_CAM_CONFIG,
} as const;

export type ScreenplayFormat = keyof typeof FORMAT_CONFIGS;

// Helper to get config by format name
export function getFormatConfig(format: ScreenplayFormat): import('./types').PageConfig {
  return FORMAT_CONFIGS[format];
}
