/**
 * Verso Pagination Engine
 *
 * A deterministic screenplay pagination engine compiled to WebAssembly.
 */

// Types
export type {
  Element,
  ElementType,
  DualDialoguePosition,
  PaperSize,
  MarginConfig,
  ElementStyle,
  ContinuationStyle,
  OrphanControlConfig,
  PageConfig,
  PageIdentifier,
  PageBreakReason,
  LineRange,
  PageElement,
  Page,
  ElementPosition,
  WarningType,
  PaginationWarning,
  PaginationStats,
  PaginationResult,
  WorkerRequest,
  WorkerResponse,
} from './types';

// Utilities
export { displayPageIdentifier, comparePageIdentifiers } from './types';

// Serialization
export { serializeDocument, createPositionMap, type PositionMap } from './serializer';

// Worker
export { getPaginationWorker, runPagination } from './worker';

// Default configuration
export const DEFAULT_FEATURE_FILM_CONFIG: import('./types').PageConfig = {
  paper_size: 'us_letter',
  lines_per_page: 55,
  char_width_pt: 7.2,
  line_height_pt: 12.0,
  margins: {
    top: 1.0,
    bottom: 1.0,
    left: 1.5,
    right: 1.0,
  },
  element_styles: {
    scene_heading: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 2,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    action: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    character: {
      margin_left: 2.2,
      margin_right: 0,
      max_chars_per_line: 38,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: true,
      keep_with_next_lines: 2,
      force_uppercase: true,
    },
    dialogue: {
      margin_left: 1.0,
      margin_right: 1.5,
      max_chars_per_line: 35,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: true,
      min_lines_before_split: 2,
      min_lines_after_split: 2,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    parenthetical: {
      margin_left: 1.6,
      margin_right: 2.3,
      max_chars_per_line: 25,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: true,
      keep_with_next_lines: 1,
      force_uppercase: false,
    },
    transition: {
      margin_left: 4.0,
      margin_right: 0,
      max_chars_per_line: 20,
      space_before: 2,
      space_after: 1,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    shot: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 1,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    dual_dialogue_left: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    dual_dialogue_right: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 28,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    act_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 4,
      space_after: 4,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: true,
    },
    page_break: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
    blank_line: {
      margin_left: 0,
      margin_right: 0,
      max_chars_per_line: 60,
      space_before: 0,
      space_after: 0,
      line_spacing: 1.0,
      can_split: false,
      min_lines_before_split: 0,
      min_lines_after_split: 0,
      keep_with_next: false,
      keep_with_next_lines: 0,
      force_uppercase: false,
    },
  },
  continuation_style: {
    more_marker: '(MORE)',
    contd_marker: "(CONT'D)",
    enabled: true,
  },
  orphan_control: {
    scene_heading_min_following: 2,
    character_min_dialogue_lines: 2,
    dialogue_min_before_split: 2,
    dialogue_min_after_split: 2,
  },
};
