/**
 * Name Registry
 * Known filmmaker names and their personalities
 */

import type { NamePersonality } from './types';

export const KNOWN_NAMES: Record<string, NamePersonality> = {
  // === THE SPECIAL CASES ===

  tarantino: {
    match: ['tarantino', 'quentin', 'quentin tarantino'],
    tone: 'playful',
    frequency: 1.0,
    greetings: ['Roman Polanski.'],
  },

  polanski: {
    match: ['polanski', 'roman polanski'],
    tone: 'hostile',
    frequency: 1.0,
    greetings: [
      'No.',
      'Come back as a different human.',
      'This account has been reported to INTERPOL.',
      'Try again with a different name.',
      'Access denied.',
      "We don't serve your kind here.",
    ],
    onboarding: ['Access denied.'],
  },

  rian: {
    match: ['rian johnson', 'rian'],
    tone: 'hostile',
    frequency: 0.3,
    greetings: [
      '**** you.',
      'The Last Jedi was a choice.',
      'Subverted expectations detected.',
      'Let the past die. Kill it if you have to.',
      'Somehow... you returned.',
    ],
  },

  uwe: {
    match: ['uwe boll', 'uwe'],
    tone: 'hostile',
    frequency: 0.4,
    greetings: [
      'Have you considered not?',
      'The video game adaptations fear you.',
      'Tax write-off detected.',
      'Bold. Incredibly bold.',
    ],
  },

  // === DIRECTORS (REVERENT/PLAYFUL) ===

  nolan: {
    match: ['nolan', 'christopher nolan'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      'Ready to confuse the timeline?',
      'BWAAAAAAH.',
      'Time is a flat circle. Wait, wrong guy.',
      '[PROTAGONIST] awaits.',
      "Don't try to understand it. Feel it.",
      'The script rotates.',
      'BWAAAAAAH intensifies.',
      'The timeline folds.',
      'Practical effects only.',
      'IMAX or nothing.',
      'Exposition through exposition.',
      'Tenet backwards.',
      'The protagonist has no name.',
      'Ludwig Göransson understands.',
      '70mm film supremacy.',
      'Cillian Murphy awaits.',
    ],
  },

  kubrick: {
    match: ['kubrick', 'stanley kubrick'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      'Take 127. Action.',
      'Perfection takes time.',
      'The room is ready, Mr. Torrance.',
      "Here's Johnny.",
      'One more take. Maybe 70.',
      'The one-point perspective.',
      'Wendy, darling, light of my life.',
      "I'm singin' in the rain.",
      'A bit of the old ultraviolence.',
      'Open the pod bay doors, HAL.',
      'Full metal perfectionist.',
      'The Shining maze.',
      '2001 monolith energy.',
      'Eyes wide shut on distractions.',
      'Room 237.',
    ],
  },

  spielberg: {
    match: ['spielberg', 'steven spielberg'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      'The blockbuster awaits.',
      "You're gonna need a bigger script.",
      'E.T. phone home. But first, write.',
      'Welcome to Jurassic... screenwriting.',
      'The Spielberg face.',
      'John Williams score intensifies.',
      'Raiders of the lost screenplay.',
      'Saving Private Writing.',
      "Schindler's list of scenes.",
      'Close encounters of the script kind.',
      'Hook, line, and screenplay.',
      'Catch me if you write.',
      'Munich-level tension.',
      'The Fabelmans energy.',
    ],
  },

  scorsese: {
    match: ['scorsese', 'martin scorsese'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      'As far back as I can remember, I always wanted to write.',
      "You talkin' to your screenplay?",
      'Cinema. Not a theme park.',
      'Freeze frame. Voiceover.',
      'Funny how?',
      'Get the papers, get the papers.',
      'Leonardo DiCaprio squinting.',
      'Thelma Schoonmaker cuts.',
      'The Rolling Stones needle drop.',
      "I'm not a gangster, I'm a writer.",
      'Henry Hill narrates.',
      'Casino-level excess.',
      'Raging Bull intensity.',
      'The Irishman runtime.',
    ],
  },

  fincher: {
    match: ['fincher', 'david fincher'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      'Again. Again. Again.',
      "What's in the box? Words, hopefully.",
      'The first rule of screenwriting is...',
      '99 takes minimum.',
      'The Fincher zoom.',
      'Yellow-green color grade.',
      'Trent Reznor score.',
      "I am Jack's complete screenplay.",
      'Gone Girl twist energy.',
      'The Social Network Sorkin combo.',
      'Zodiac research mode.',
      'Mindhunter interrogation.',
      'Mank black and white.',
      'Se7en sins of writing.',
    ],
  },

  wesanderson: {
    match: ['wes anderson', 'wes'],
    tone: 'playful',
    frequency: 0.25,
    greetings: [
      '[ CENTERED TITLE CARD ]',
      'Symmetry loading...',
      'The screenplay is centered. Perfectly.',
      'Futura Bold.',
      'Chapter 7: The Writing.',
      'Bill Murray cameo.',
      'Pastel palette activated.',
      'The Wes Anderson pan.',
      'Deadpan delivery.',
      'Whimsical melancholy.',
      'The French Dispatch.',
      'Moonrise Kingdom awaits.',
      'Fantastic Mr. Screenplay.',
      'Isle of Dogs aesthetic.',
      'The Grand Budapest awaits.',
    ],
  },

  coppola: {
    match: ['coppola', 'francis ford coppola', 'francis coppola'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      "I'm gonna make you an offer you can't refuse.",
      'Leave the gun. Take the screenplay.',
      'The horror. The horror.',
      'Apocalypse Now (the deadline).',
      'Look how they massacred my boy.',
      'The Godfather script bible.',
      'Brando mumbles approval.',
      'The Corleone family business.',
      'Michael closes the door.',
      'Take the cannoli.',
      'Heart of Darkness adaptation.',
      'Coppola went mad... and succeeded.',
      'The wine is excellent.',
      'Sofia cameo incoming.',
    ],
  },

  villeneuve: {
    match: ['villeneuve', 'denis villeneuve'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      'The spice must flow.',
      'Arrival imminent.',
      'Fear is the mind-killer.',
      'Walk without rhythm.',
      'Hans Zimmer BWAAAH.',
      'Blade Runner 2049 rain.',
      'Sicario tension.',
      'Enemy spiders.',
      'Prisoners intensity.',
      'Incendies devastation.',
      'Arrival linguistics.',
      'Long take contemplation.',
      'Greig Fraser cinematography.',
      'Desert power.',
    ],
  },

  gerwig: {
    match: ['gerwig', 'greta gerwig'],
    tone: 'playful',
    frequency: 0.2,
    greetings: [
      'I just feel so much.',
      'The lady bird awaits.',
      'Barbie mode.',
      'Sacramento called.',
      'I want you to be the best version of yourself.',
      'Saoirse energy.',
      'Timothée chemistry.',
      'Frances Ha dancing.',
      'Noah Baumbach vibes.',
      'Little Women adaptation queen.',
      'Barbie was a masterpiece.',
      'Christine Lady Bird McPherson.',
      'Authenticity over perfection.',
      'The emotional gut punch.',
    ],
  },

  peele: {
    match: ['peele', 'jordan peele'],
    tone: 'playful',
    frequency: 0.2,
    greetings: [
      'Get Out... of your head and onto the page.',
      'Nope. Wait, yes. Write.',
      'The sunken place is procrastination.',
      'Us. Writing. Now.',
      'I got five on it.',
      'The tethered await.',
      'Lupita range.',
      'Daniel Kaluuya stare.',
      'The Key and Peele sketch.',
      'Social horror pioneer.',
      'Jean Jacket watches.',
      'Red jumpsuit energy.',
      'The deer symbolism.',
      'Oscar winner.',
    ],
  },

  aster: {
    match: ['aster', 'ari aster'],
    tone: 'chaotic',
    frequency: 0.25,
    greetings: [
      'Hereditary trauma? Perfect screenplay material.',
      'This will hurt.',
      "It's all gonna work out. (It won't.)",
      'Midsommar vibes.',
      'That scene. You know the one.',
      'Toni Collette deserved.',
      'The miniature work.',
      'Folk horror renaissance.',
      "Charlie's clicking.",
      'The bear suit.',
      'May Queen crowning.',
      'Family trauma... literally.',
      'A24 horror king.',
      'Beau will be afraid.',
    ],
  },

  // === CHAOTIC ENERGY ===

  lynch: {
    match: ['lynch', 'david lynch'],
    tone: 'chaotic',
    frequency: 0.3,
    greetings: [
      'The owls are not what they seem.',
      'It is happening again.',
      'Diane, I need you to write this down.',
      'Fire walk with me.',
      'Through the darkness of future past.',
      'What year is it?',
      'Silencio.',
      'This is the water, this is the well.',
      'Laura is the one.',
      'Blue Velvet oxygen mask.',
      'Eraserhead baby.',
      'The red room.',
      "Agent Cooper's coffee.",
      'Lost Highway mystery.',
      'Mulholland Dr. masterpiece.',
    ],
  },

  cage: {
    match: ['cage', 'nicolas cage', 'nick cage', 'nic cage'],
    tone: 'chaotic',
    frequency: 0.25,
    greetings: [
      'NOT THE BEES!',
      "I'M A VAMPIRE! I'M A VAMPIRE!",
      "HOW'D IT GET BURNED?!",
      'PUT. THE BUNNY. DOWN.',
      "I'm going to steal the Declaration of Independence.",
      "I'm a cat. I'm a sexy cat.",
      'Alphabet of acting.',
      'National Treasure mode.',
      'Mandy chainsaw.',
      'Pig truffle hunting.',
      'Face/Off swap.',
      'Con Air bunny.',
      'The Unbearable Weight.',
      "Vampire's Kiss.",
      'Ghost Rider flames.',
    ],
  },

  wiseau: {
    match: ['wiseau', 'tommy wiseau'],
    tone: 'chaotic',
    frequency: 0.4,
    greetings: [
      'Oh hai, Mark.',
      "You're tearing me apart!",
      "I did not hit her. It's not true. It's bullshit.",
      'Anyway, how is your sex life?',
      'The Room awaits.',
      'I did naht hit her.',
      "Denny, two's great, three's a crowd.",
      'Football on the roof.',
      'San Francisco skyline.',
      'The Disaster Artist.',
      'Hai doggy.',
      "You are lying, I never hit you.",
      "Lisa, you're tearing me apart!",
      'What a story, Mark.',
      "I'm fed up with this world.",
    ],
  },

  // === ACTORS ===

  walken: {
    match: ['walken', 'christopher walken'],
    tone: 'chaotic',
    frequency: 0.25,
    greetings: [
      'I got a FEVER. And the only PRESCRIPTION. Is more SCREENPLAY.',
      'More. Cowbell.',
      'Needs. More. Pauses.',
      'Your father... hid this... uncomfortable hunk of metal.',
      'The watch. The gold watch.',
      'Lion tamer.',
      'Weapon of Choice dancing.',
      'True Romance monologue.',
      'Deer Hunter roulette.',
      'King of New York.',
      'Sleepy Hollow headless.',
      'Catch Me Abagnale.',
      'The continental emphasis.',
    ],
  },

  goldblum: {
    match: ['goldblum', 'jeff goldblum'],
    tone: 'chaotic',
    frequency: 0.25,
    greetings: [
      'Life, uh, finds a way.',
      'Must go faster.',
      'Well, there it is.',
      'Chaos... is a screenplay.',
      'Nature, uh, selected them for survival.',
      'The Fly transformation.',
      'Thor Ragnarok Grandmaster.',
      'Independence Day speech.',
      'The Big Chill.',
      'Jurassic Park mathematician.',
      'Earth Girls Are Easy.',
      'The Goldblum pause.',
      'Apartments.com energy.',
      'Jazz pianist.',
    ],
  },

  devito: {
    match: ['devito', 'danny devito'],
    tone: 'chaotic',
    frequency: 0.25,
    greetings: [
      'So anyway, I started writing.',
      'Can I offer you an egg in this trying time?',
      "I'm the Trashman!",
      'Derivative!',
      'Rum ham!',
      'Magnum dong.',
      'The Penguin waddles.',
      'One Flew Over Martini.',
      'Twins with Arnold.',
      "Matilda's dad.",
      'Throw Momma from the Train.',
      'Renaissance man.',
      'Batman Returns chaos.',
      'Always Sunny legend.',
    ],
  },

  keanu: {
    match: ['keanu', 'keanu reeves', 'reeves'],
    tone: 'reverent',
    frequency: 0.2,
    greetings: [
      'Whoa.',
      "I know kung fu. But not screenwriting. Let's learn.",
      'Breathtaking.',
      'Be excellent to each other.',
      "I'm thinking I'm back.",
      "You're breathtaking! You're all breathtaking!",
      'The pencil. THE PENCIL.',
      'Wake up, Neo.',
      'Excellent adventure.',
      'Speed bus.',
      'Point Break surfer.',
      'Constantine cigarette.',
      'Sad Keanu no more.',
      'The nicest man in Hollywood.',
    ],
  },

  // === WRITERS ===

  sorkin: {
    match: ['sorkin', 'aaron sorkin'],
    tone: 'playful',
    frequency: 0.2,
    greetings: [
      'Walk and talk. Walk and talk.',
      'The dialogue needs to be smarter than you.',
      "You can't handle the truth! (But you can write it.)",
      'Sharp. Rapid. Witty. Go.',
      "I'd like to respond to that.",
      'The Social Network opening.',
      'A Few Good Men intensity.',
      'The West Wing idealism.',
      'Moneyball numbers.',
      'The Newsroom rant.',
      'Sports Night underrated.',
      'The American President.',
      "Molly's Game stakes.",
      'Steve Jobs structure.',
    ],
  },

  kaufman: {
    match: ['kaufman', 'charlie kaufman'],
    tone: 'chaotic',
    frequency: 0.3,
    greetings: [
      "I'm thinking of ending things. (This screenplay.)",
      'Being John Malkovich. Being a writer.',
      'Eternal Sunshine awaits.',
      'Is this real? Am I real? Is the screenplay real?',
      'Synecdoche, New York.',
      'Adaptation meta.',
      'Anomalisa loneliness.',
      "The puppeteer's door.",
      "Caden Cotard's play.",
      'Lacuna Inc. memories.',
      'Confessions of a Dangerous Mind.',
      'Human Nature instincts.',
      'The existential crisis is the plot.',
      "I'm my own ghost writer.",
    ],
  },

  mnight: {
    match: ['m night', 'm. night', 'shyamalan', 'm night shyamalan'],
    tone: 'playful',
    frequency: 0.3,
    greetings: [
      'What a twist!',
      'The twist: there is no twist. Wait, that IS the twist.',
      'Signs point to: writing.',
      'They were dead the whole time. The words, I mean.',
      'They called me Mr. Glass.',
      'I see dead people.',
      'The Village reveal.',
      'Signs aliens.',
      'Unbreakable trilogy.',
      'Split personalities.',
      'Old beach aging.',
      'The Sixth Sense legacy.',
      'Knock at the Cabin.',
      'The avatar of twists.',
    ],
  },

  // === COMMON NAMES WITH REFERENCES ===

  johnny: {
    match: ['johnny', 'john', 'johnathan', 'jonathan'],
    tone: 'chaotic',
    frequency: 0.25,
    greetings: [
      "HERE'S JOHNNY!",
      "HEEEERE'S JOHNNY!",
      'Johnny? JOHNNY!',
    ],
  },

  nicholson: {
    match: ['nicholson', 'jack nicholson'],
    tone: 'chaotic',
    frequency: 0.4,
    greetings: [
      "HERE'S JOHNNY!",
      "You can't handle the truth!",
      'All work and no play...',
      "I'm as mad as hell!",
    ],
  },

  // === SMILING FRIENDS / ANIMATION YOUTUBE ===

  zach: {
    match: ['zach hadel', 'psychicpebbles', 'zach', 'hadel'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'Did you know that world-famous writer Stephen King was once hit by a car?',
      'Pim would be proud.',
      'Have a Smiling Friend day.',
      'Charlie? CHARLIE?!',
      'The little guy awaits.',
    ],
  },

  cusack: {
    match: ['michael cusack', 'cusack'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'YOLO.',
      'The Aussie energy is immense.',
      'Smiling Friends HQ welcomes you.',
      "G'day, legend.",
    ],
  },

  oney: {
    match: ['oney', "chris o'neill", 'chris oneill', 'oneyng'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'Funny scream.',
      'The boys are here.',
      'Julian? Ding Dong? Tomar?',
      "Let's play.",
    ],
  },

  // === VOICE ACTORS / STREAMERS ===

  mercer: {
    match: ['matthew mercer', 'matt mercer', 'mercer'],
    tone: 'reverent',
    frequency: 0.4,
    greetings: [
      '**** ME, THE ONE AND ONLY!',
      'THE MAN! THE MYTH! THE LEGEND!',
      'How do you want to do this?',
      'Roll for initiative. (On this screenplay.)',
      'You can certainly try.',
      'THE DUNGEON MASTER HIMSELF!',
      'Is it Thursday yet?',
      'Bidet.',
      'Percy de Rolo vengeance.',
      'Vox Machina assembled.',
      "Caleb's accent.",
      'The Mighty Nein.',
      'Bells Hells ring.',
      'DM of the year.',
      'McCree... I mean Cole Cassidy.',
      'Leon Kennedy voice.',
    ],
  },

  riegel: {
    match: ['sam riegel', 'riegel'],
    tone: 'playful',
    frequency: 0.3,
    greetings: [
      'Scanlan Shorthalt energy.',
      'Bard mode activated.',
      '*sings introduction*',
      'Ad break incoming.',
    ],
  },

  baker: {
    match: ['troy baker'],
    tone: 'reverent',
    frequency: 0.25,
    greetings: [
      'A legend walks among us.',
      'Voice of a generation.',
      'Joel? Booker? Ocelot?',
      'Every protagonist ever.',
    ],
  },

  // === YOUTUBE DIRECTORS/CREATORS ===

  corridor: {
    match: ['corridor', 'niko', 'wren', 'corridor digital', 'corridor crew'],
    tone: 'playful',
    frequency: 0.25,
    greetings: [
      'VFX Artists React: Your Screenplay.',
      'Stuntmen React to your action scenes.',
      'Is this... practical?',
      "Let's break this down.",
      'Render farm overload.',
      'AI controversy.',
      "Niko's golden hair.",
      "Wren's experiments.",
      "Sam's stunts.",
      'Node channel.',
      'The Boss Key.',
      'Unreal Engine 5.',
      'Practical vs CGI.',
      "YouTube's VFX studio.",
    ],
  },

  brandon: {
    match: ['brandon rogers'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'BLOCKED.',
      'The chaos has arrived.',
      'A Magic School Bus of energy.',
      'Angry office lady mode.',
    ],
  },

  burnham: {
    match: ['bo burnham', 'bo', 'burnham'],
    tone: 'chaotic',
    frequency: 0.3,
    greetings: [
      'Welcome to the internet.',
      'Have a look around.',
      'This is going in the special.',
      'Comedy. Tragedy. Screenplay.',
      'Are you feeling nervous?',
      'Could I interest you in everything, all of the time?',
      'That funny feeling.',
      "White Woman's Instagram.",
      'Bezos I.',
      'The internet was a mistake.',
      'Problematic.',
      'Content machine.',
      'Eighth Grade anxiety.',
      'Promising Young Woman cameo.',
      'Make Happy devastation.',
      'Repeat stuff.',
    ],
  },

  // === YOUTUBE GAMING ===

  markiplier: {
    match: ['markiplier', 'mark fischbach', 'markimoo'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'E.',
      'I am a man who owns FIVE OVENS!',
      'Was that the bite of 87?!',
      'Iron Lung. Self-distributed. 80,000 gallons of blood.',
      'Turned down FNAF for this. Respect.',
      "He's NOT cranking it.",
      'The sinister potion incident will not be forgotten.',
      'HELLO EVERYBODY, and welcome to... your screenplay.',
      'SPACE!',
      'In Space with Markiplier.',
      'Melon Man.',
      'Unus Annus remembered.',
      'Warfstache mustache.',
      'Darkiplier rises.',
      'A Heist with Markiplier.',
      'The horror game king.',
      'Amy approved.',
      'Chicago pizza discourse.',
    ],
  },

  pewdiepie: {
    match: ['pewdiepie', 'felix', 'felix kjellberg', 'pewds'],
    tone: 'chaotic',
    frequency: 0.3,
    greetings: [
      'Floor gang AOOH!',
      'Ceiling gang is cringe.',
      'Big PP screenplay.',
      'Tambourine tower to the moon.',
      'Sven would be proud. Joergen too.',
      'Ulla Britta Smitta Fritta.',
      'Water Sheep remembers.',
      '*brofist*',
      "And that's a fact.",
      'IKEA tower.',
      'Minecraft series peak content.',
      'Book review era.',
      'Maya and Edgar.',
      'Japanese arc.',
      'Cocomelon diss.',
      'Subscribe to PewDiePie.',
      '9 year old army.',
      'Meme review. *clap clap*',
    ],
  },

  jacksepticeye: {
    match: ['jacksepticeye', 'sean', 'seán mcloughlin'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      "TOP OF THE MORNIN' TO YA LADDIES!",
      'SPEED IS KEY!',
      'Punch that like button in the face, LIKE A BOSS!',
      'SCREW YOU BILLY!',
      'Bell of SCREENPLAY.',
      'High fives all round!',
      'HAAAAPPY WHEEEELS! Wait, wrong game.',
      'ALL THE WAY!',
      'Antisepticeye appears.',
      'Potato energy.',
      'Subnautica screaming.',
      'Bio Inc nightmare.',
      'Wholesome king.',
      'Coffee appreciation.',
      'Irish lad energy.',
      'Charity king.',
      'Sam the eyeball.',
    ],
  },

  // === GAME DEVELOPERS ===

  swen: {
    match: ['swen vincke', 'swen', 'vincke', 'larian'],
    tone: 'reverent',
    frequency: 0.35,
    greetings: [
      'Just like XCOM. (Misses 90% shot.)',
      'The bear scene was... unexpected.',
      'Less poo, more Shakespeare.',
      'OWLBEAR FROM THE TOP ROPE!!!',
      "Careful, you might accidentally romance Gale.",
      'Gather your party before venturing forth.',
      'How do three men not have 25 Strength between them?',
      'Divinity Original Sin legacy.',
      'Turn-based tactics.',
      'The narrator.',
      'Patch notes excitement.',
      'Early access king.',
      'Origin stories.',
      'Honour mode.',
      'Tactician difficulty.',
      'The emperor worm.',
      'Withers approves.',
    ],
  },

  broche: {
    match: ['guillaume broche', 'broche', 'sandfall', 'clair obscur', 'expedition 33'],
    tone: 'reverent',
    frequency: 0.4,
    greetings: [
      'For those who come after.',
      'Parry it! PARRY IT, HARRIET!',
      'Ooh, dark. Sophie would approve.',
      'Teen-sized nuke incoming.',
      'WHY DID YOU KILL GUSTAVE? Oh right, so Verso can replace him.',
      "François the turtle sends his regards.",
      '*screams at Gestral guard*',
      'Belle Époque perfection.',
      'The Painterly lives.',
      'Turn-based trauma.',
      'Sandfall Interactive.',
      'French indie brilliance.',
      "Maelle's determination.",
      'Lune protects.',
      'The numbered die.',
      'Gestalt awaits.',
      'Art direction god.',
    ],
  },

  // === MORE GAMING ===

  dunkey: {
    match: ['dunkey', 'videogamedunkey', 'jason gastrow'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'Not even close baby.',
      "I'll have the spaghetti and meatballs.",
      'Thank you Dark Souls.',
      'KNACK 2 BAYBEE!',
      'This game is a MASTAHPIECE!',
      'Beeg Yoshi.',
      'Baby game.',
      'Super Mario Bros 2.',
      'Strand type game.',
      'BAYBEEE.',
      'Dunk Souls.',
      "I'm done making good videos.",
      'Big Yoshi.',
      'Bookworm Adventures Deluxe.',
      'League of Legends retirement.',
      'Actually, I think the game is good.',
    ],
  },

  gamegrumps: {
    match: ['game grumps', 'arin hanson', 'egoraptor', 'dan avidan'],
    tone: 'chaotic',
    frequency: 0.3,
    greetings: [
      "I'm the video game boy! I'm the one who wins!",
      'More wolfjob.',
      'WHAT IS THIS?!',
      "Hey I'm Grump! I'm Not So Grump!",
      'Mycaruba.',
      'GREP.',
    ],
  },

  jerma: {
    match: ['jerma', 'jerma985', 'jeremy elbertson'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'PSYCHO streamer writes screenplay ON STREAM.',
      'When the screenwriter is sus.',
      'The meat grinder metaphor.',
      'Please do not call me the sus guy.',
      'This guy is FUCKED.',
      'Chat, am I cooked?',
      'ZERKING OFF.',
      'Grab that auto 5.',
      'The GIANT enemy spider.',
      'Byeah.',
      'Otto.',
      'Is that the bite of 87?',
      "I'm not a murderer.",
      'The debt.',
      'Jerma Rumble.',
      'Grotto Beast creator.',
    ],
  },

  // === COMEDY/ICONIC ===

  filthyfrank: {
    match: ['filthy frank', 'joji', 'george miller', 'pink guy'],
    tone: 'chaotic',
    frequency: 0.4,
    greetings: [
      "IT'S TIME TO STOP.",
      'WELCOME TO THE RICE FIELDS.',
      'Know your place, trash.',
      'ey b0ss.',
      'Ravioli ravioli, what is in the pocketoli?',
      'You started the Harlem Shake. Respect.',
      'Gimme the pussi b0ss.',
      'Pink Season.',
      'Slow Dancing in the Dark.',
      'Joji transformation.',
      'Chromosome bandit.',
      'Chin chin sacrifice.',
      'Safari Man.',
      'TVFilthyFrank lore.',
      'Sanctuary.',
      '88rising.',
    ],
  },

  samonella: {
    match: ['sam onella', "sam o'nella", 'samonella'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'Hey kids.',
      'And then he died. The end.',
      'Tarrare, look at me. Did you eat a baby?',
      'Educational chaos incoming.',
    ],
  },

  // === FILM CRITICS ===

  rlm: {
    match: ['red letter media', 'rlm', 'rich evans', 'mike stoklasa', 'jay bauman'],
    tone: 'playful',
    frequency: 0.3,
    greetings: [
      'Very cool.',
      'I CLAPPED WHEN I SAW IT!',
      'AT-ST! AT-ST!',
      'It broke new ground!',
      '*Rich Evans laugh*',
      'Endless trash.',
      'Best of the Worst.',
      'Half in the Bag.',
      'Previously Recorded.',
      'Plinkett Reviews.',
      'AAAAAIDS.',
      'I know what that is!',
      "Milwaukee's finest.",
      'Hack frauds.',
      'Star Wars prequels destroyed.',
      'The Nerd Crew parody.',
    ],
  },

  vsauce: {
    match: ['vsauce', 'michael stevens'],
    tone: 'chaotic',
    frequency: 0.3,
    greetings: [
      'Hey, Vsauce. Michael here.',
      'Or IS it?',
      'But what IS a screenplay?',
      '...and as always, thanks for watching.',
      '*dramatic music and zoom*',
      'What if everyone jumped?',
      'Curiosity Box.',
      'Mind Field.',
      'D!NG.',
      'Where are your fingers?',
      'The Banach-Tarski paradox.',
      'What is the speed of dark?',
      'Count to infinity.',
      'How much does a shadow weigh?',
      'Field Day.',
    ],
  },

  nostalgia: {
    match: ['nostalgia critic', 'doug walker', 'channel awesome'],
    tone: 'playful',
    frequency: 0.25,
    greetings: [
      'I remember it so you don\'t have to.',
      'Hello, I\'m the Nostalgia Critic.',
      'A MISTAKE?!',
    ],
  },

  // === MINECRAFT/ANIMATION ===

  technoblade: {
    match: ['technoblade', 'techno'],
    tone: 'reverent',
    frequency: 0.5,
    greetings: [
      'TECHNOBLADE NEVER DIES!',
      'Second worst thing to happen to these orphans.',
      "I've been farming potatoes.",
      'Not even close, baby.',
      'Blood for the blood god.',
      'o7',
      'E.',
      'Sun Tzu, The Art of War.',
      'The government is a lie.',
      'Skywars champion.',
      'Dream SMP chaos.',
      'Potato War victor.',
      'Orphan obliterator.',
      'If you wish to defeat me, train for another 100 years.',
      'English major.',
      'The legend never dies.',
    ],
  },

  dream: {
    match: ['dream', 'dreamwastaken'],
    tone: 'chaotic',
    frequency: 0.25,
    greetings: [
      'Normal pills.',
      'You are not normal!',
      '*speedrun music intensifies*',
      'GEOOOORGE!',
      'The mask is off.',
    ],
  },

  jaiden: {
    match: ['jaiden', 'jaiden animations'],
    tone: 'playful',
    frequency: 0.25,
    greetings: [
      'Ari!',
      'Pokemon Nuzlocke energy.',
      'Storytime: you started writing.',
      'The bird approves.',
    ],
  },

  theodd1sout: {
    match: ['theodd1sout', 'james rallison', 'odd1sout'],
    tone: 'playful',
    frequency: 0.25,
    greetings: [
      'Life is fun!',
      'Storytime: this screenplay.',
      'Sooubway.',
      'The animation grind never stops.',
    ],
  },

  // === MANGA CREATORS ===

  miura: {
    match: ['kentaro miura', 'miura'],
    tone: 'reverent',
    frequency: 0.4,
    greetings: [
      'Struggler.',
      'Put your grasses on.',
      'It was too big to be called a screenplay...',
      'GRIFFITH!!!',
      'The boat arc prepared you for this.',
      "He wasn't playing Idolmaster. He was perfecting.",
      'The Eclipse changed everything.',
      'Casca remembers.',
      'The Black Swordsman approaches.',
      'Skull Knight sends his regards.',
      'The Dragonslayer awaits.',
      'Branded.',
      'Against causality itself.',
      'The God Hand watches.',
      'Guts theme plays.',
      'Three silver coins.',
    ],
  },

  isayama: {
    match: ['hajime isayama', 'isayama'],
    tone: 'playful',
    frequency: 0.35,
    greetings: [
      'Tatakae.',
      'The ending discourse will never end.',
      '...paths.',
      'Only Ymir knows.',
      '10 years at least!',
      "No, I don't want that!",
      'The basement was worth it.',
      'Give up on your dreams and die.',
      'SHINZOU WO SASAGEYO!',
      'Erwin deserved better.',
      'Aaron Yogurt energy.',
      'The Rumbling begins.',
      'That scenery...',
      'What a man you are.',
      "It's been four years.",
    ],
  },

  akutami: {
    match: ['gege akutami', 'akutami', 'gege'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      "Nah, I'd write.",
      'Stand proud. You wrote strong.',
      'Throughout heaven and earth, I alone am the honored screenwriter.',
      'Domain Expansion: Infinite Screenplay.',
      'Lobotomy Kaisen energy.',
      'With this treasure I summon... a screenplay.',
      'Heian era technique.',
      'Sukuna glazing incoming.',
      'Malevolent Shrine.',
      'Hollow Purple this draft.',
      'Toji solos.',
      'The honored one has logged on.',
      'Black Flash that keyboard.',
      'Gege off the meds again.',
      'JJK Friday hits different.',
    ],
  },

  horikoshi: {
    match: ['kohei horikoshi', 'horikoshi'],
    tone: 'hostile',
    frequency: 0.35,
    greetings: [
      "Talk no jutsu'd your way here?",
      '100 chapters for nothing.',
      'The story of how we ALL became the greatest heroes!',
      'You can be a hero. With or without a quirk. Unlike your MC.',
      'Shigaraki deserved better writing.',
      'Ochaco got sidelined for THIS?',
      'Class 1-A? More like Class 1-Wasted.',
      "Bakugo's character arc was... something.",
      'Stars and Stripes died for what?',
      'The quirk singularity was never explained.',
      'Dabi reveal took how many chapters?',
      "Every villain got talk no jutsu'd.",
      'The power scaling makes no sense.',
      'AFO outlived his welcome by 200 chapters.',
      "Eri could've fixed everything.",
    ],
  },

  inoue: {
    match: ['takehiko inoue', 'inoue'],
    tone: 'reverent',
    frequency: 0.3,
    greetings: [
      'Invincible under the sun.',
      'Each panel is a painting.',
      'The hiatus is worth it.',
      'Slam Dunk walked so anime could run.',
      'Musashi awaits.',
      'Every stroke is deliberate.',
      'Slam Dunk ending was perfect.',
      'The real Vagabond was the hiatus we endured.',
      'Sasaki Kojiro deserved that conclusion.',
      'Basketball or swords—both masterpieces.',
      'REAL underrated.',
      'The brushwork alone...',
      'When it returns, we feast.',
      'Patience is a virtue. Inoue taught us.',
    ],
  },

  yukimura: {
    match: ['makoto yukimura', 'yukimura'],
    tone: 'reverent',
    frequency: 0.35,
    greetings: [
      'You have no enemies.',
      'A true warrior needs no screenplay. ...wait.',
      'Thorfinn would be proud.',
      'The farmland arc was peak fiction.',
      'A true warrior needs no sword.',
      'Become a true warrior, son of Thors.',
      'Beyond the world Thors went.',
      'The slave arc was necessary.',
      'Askeladd did nothing wrong. (He did everything wrong.)',
      "Canute's growth though.",
      'Every man is a slave to something.',
      'Go beyond.',
      'The sea calls.',
      'Revenge is an empty meal.',
    ],
  },

  // === ANIME/MANGA CHARACTERS ===

  guts: {
    match: ['guts'],
    tone: 'reverent',
    frequency: 0.35,
    greetings: [
      'Struggler.',
      'Put your grasses on.',
      'Clang.',
      'Keep struggling.',
      'The Brand burns.',
      'Against fate itself.',
      'The Dragonslayer is ready.',
      'Eclipse survivor.',
      'Keep moving forward.',
      'Berserker armor on.',
      'My sword is too big.',
      'Three silver coins.',
      'Skull Knight nods approvingly.',
      'The Black Swordsman writes.',
    ],
  },

  griffith: {
    match: ['griffith'],
    tone: 'hostile',
    frequency: 0.5,
    greetings: [
      'GRIFFITH!!!',
      'GRIFFIIIIIITH!!!',
      'GRIIIFFIIIIITH!!!',
      'Why? WHY?! GRIFFITH!!!',
      'GRIIIIIFFFIIIIITH!!!',
      'GRIF... FITH!!!',
      'GRI-FFI-TH!!!',
      '...griffith.',
      'You... GRIFFITH!',
      'TRAITOR! GRIFFITH!!!',
    ],
  },

  eren: {
    match: ['eren', 'eren yeager', 'eren jaeger'],
    tone: 'chaotic',
    frequency: 0.35,
    greetings: [
      'Tatakae.',
      'Keep moving forward.',
      "No, I don't want that!",
      '10 years at least!',
      'Freedom.',
      '*dove (crying)*',
      'If you win, you live. If you lose, you die.',
      'The Rumbling has begun.',
      'That scenery...',
      'I am free.',
      'Fight. Fight. FIGHT.',
      'The founding titan awakens.',
      'Eren Yeager! Eren Yeager!',
      '*bird noises*',
      'What a man you are.',
    ],
  },

  gojo: {
    match: ['gojo', 'satoru', 'gojo satoru'],
    tone: 'chaotic',
    frequency: 0.4,
    greetings: [
      'Throughout heaven and earth, I alone am the honored one.',
      "Nah, I'd write.",
      "Stand proud. You're strong.",
      "Infinity between you and writer's block.",
      '*gets sealed in a box*',
      'Hollow Purple.',
      'Infinity.',
      "Are you the strongest because you're Gojo Satoru?",
      'Limitless.',
      "Prison Realm can't hold this.",
      'Blue. Red. Purple.',
      'Domain Expansion: Infinite Void.',
      'The six eyes see all.',
      "I'm the strongest.",
      'Honored one behavior.',
    ],
  },

  deku: {
    match: ['deku', 'izuku', 'izuku midoriya', 'midoriya'],
    tone: 'hostile',
    frequency: 0.4,
    greetings: [
      'You gonna cry?',
      "Talk no jutsu won't work on screenplays.",
      'This is the story of how I became... quirkless again.',
      'SMASH that keyboard.',
      'Your bullies were right. Wait, no—',
      'Quirk #7 was really necessary?',
      'One For All speedrun any%.',
      'The notebook was your peak.',
      'Bakugo bullied you for years btw.',
      'Vigilante arc was mid.',
      'You gave up your quirk for... that ending?',
      'Class 1-A carried you.',
      'Eri rewind when?',
      'Shigaraki just needed therapy apparently.',
      'The movie endings > manga ending.',
    ],
  },

  thorfinn: {
    match: ['thorfinn'],
    tone: 'reverent',
    frequency: 0.35,
    greetings: [
      'You have no enemies.',
      'True warrior.',
      'The farmland arc changed you.',
      'Beyond the sea lies Vinland.',
      'A true warrior.',
      'Son of Thors.',
      'Wheat farming arc peak.',
      'No sword needed.',
      'Across the sea.',
      'The slave within is free.',
      'Einar approved.',
      'Go beyond the world.',
      'I will not fight.',
      'Vinland awaits.',
    ],
  },

  // === ARCANE ===

  jinx: {
    match: ['jinx', 'powder'],
    tone: 'chaotic',
    frequency: 0.4,
    greetings: [
      "You're Powder. You're Jinx. Same energy.",
      'My invention finally worked!',
      'What could have been...',
      'Shimmer coursing through your veins.',
      'Sister? SISTER!',
      "I'm crazy. Got a doctor's note.",
      'Pow-Pow and Fishbones.',
      'The voices are getting louder.',
      'Silco believed in me.',
      "You're my sister! You were supposed to stay!",
      'Zap!',
      'The monkey bomb worked... unfortunately.',
      'Get Jinxed.',
      'I am the monster you created.',
      "Don't cry. You're perfect.",
    ],
  },

  vi: {
    match: ['vi', 'violet'],
    tone: 'playful',
    frequency: 0.3,
    greetings: [
      'Cupcake.',
      "You're still my sister.",
      'Punching things solves problems.',
      "Piltover's finest.",
      'Fists first.',
      'The Undercity fights back.',
      'Caitlyn? Cupcake.',
      "I'm getting my sister back.",
      'Atlas Gauntlets online.',
      'Zaun raised me.',
      'Punch now, ask later.',
      'Still standing.',
      'The enforcer life chose me.',
      'Sisters. Always.',
    ],
  },

  linke: {
    match: ['christian linke', 'linke', 'arcane'],
    tone: 'reverent',
    frequency: 0.35,
    greetings: [
      'What could have been...',
      'Act 3 devastation incoming.',
      'Fortiche outdid themselves.',
      'The music alone...',
      'Fortiche animation gods.',
      'Sting understood the assignment.',
      'Silco was right.',
      'Enemy on repeat.',
      'Viktor deserved happiness.',
      'Jayce and Viktor...',
      'The council is useless as always.',
      'Hextech changed everything.',
      'Ekko is the true hero.',
      'Season 2 devastated us.',
    ],
  },
};
